// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_ventrix.Data;

#nullable disable

namespace api_ventrix.Migrations
{
    [DbContext(typeof(ConeccionContext))]
    [Migration("20251125024504_nueva-clase-pedido-item")]
    partial class nuevaclasepedidoitem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_Lote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<int>("Id_Pedido")
                        .HasColumnType("int");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Pedido");

                    b.HasIndex("Id_Producto");

                    b.ToTable("pedidoItems");
                });

            modelBuilder.Entity("api_ventrix.Models.Administrador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Clave_Hasheada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<int>("Nivel_Acceso")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Numero_Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tipo_Documento")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Vendedorid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Id_Negocio");

                    b.HasIndex("Vendedorid");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("api_ventrix.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("api_ventrix.Models.Comprador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Clave_Hasheada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Numero_Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tipo_Documento")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Compradores");
                });

            modelBuilder.Entity("api_ventrix.Models.Descuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Descuento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo_Descuento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor_Aplica")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_Max")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_Min")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("api_ventrix.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_comprador")
                        .HasColumnType("int");

                    b.Property<int>("Id_negocio")
                        .HasColumnType("int");

                    b.Property<int>("metodoPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("metodoPagoId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("api_ventrix.Models.Impuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PedidoItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoItemId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Impuestos");
                });

            modelBuilder.Entity("api_ventrix.Models.ImpuestoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImpuestoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImpuestoId");

                    b.ToTable("ImpuestoDetalle");
                });

            modelBuilder.Entity("api_ventrix.Models.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Compradorid")
                        .HasColumnType("int");

                    b.Property<int?>("Negocioid")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("Vendedorid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Compradorid");

                    b.HasIndex("Negocioid");

                    b.HasIndex("Vendedorid");

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("api_ventrix.Models.Negocio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.PrimitiveCollection<string>("Imagenes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlLogo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.ToTable("Negocios");
                });

            modelBuilder.Entity("api_ventrix.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion_Envio")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Entrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Envio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Pago")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_Comprador")
                        .HasColumnType("int");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<int>("Metodo_Pago")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Total_Pagar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Comprador");

                    b.HasIndex("Id_Negocio");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("api_ventrix.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_Lote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DescuentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Negocioid")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DescuentoId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("Id_Negocio");

                    b.HasIndex("Negocioid");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("api_ventrix.Models.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<int>("Id_Vendedor")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_Reporte")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("api_ventrix.Models.Vendedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Clave_Hasheada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Fecha_Fin_Plan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio_Plan")
                        .HasColumnType("datetime2");

                    b.Property<int>("Negocioid")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Numero_Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tipo_Documento")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("Negocioid");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("PedidoItem", b =>
                {
                    b.HasOne("api_ventrix.Models.Pedido", "Pedido")
                        .WithMany("PedidoItems")
                        .HasForeignKey("Id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_ventrix.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("Id_Producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("api_ventrix.Models.Administrador", b =>
                {
                    b.HasOne("api_ventrix.Models.Negocio", null)
                        .WithMany()
                        .HasForeignKey("Id_Negocio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api_ventrix.Models.Vendedor", null)
                        .WithMany("Administradores")
                        .HasForeignKey("Vendedorid");
                });

            modelBuilder.Entity("api_ventrix.Models.Descuento", b =>
                {
                    b.HasOne("api_ventrix.Models.Factura", null)
                        .WithMany("Descuentos_aplicados")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("api_ventrix.Models.Factura", b =>
                {
                    b.HasOne("api_ventrix.Models.MetodoPago", "metodoPago")
                        .WithMany()
                        .HasForeignKey("metodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("metodoPago");
                });

            modelBuilder.Entity("api_ventrix.Models.Impuesto", b =>
                {
                    b.HasOne("PedidoItem", null)
                        .WithMany("Impuestos_Aplicados")
                        .HasForeignKey("PedidoItemId");

                    b.HasOne("api_ventrix.Models.Producto", null)
                        .WithMany("Impuestos_Aplicados")
                        .HasForeignKey("ProductoId");
                });

            modelBuilder.Entity("api_ventrix.Models.ImpuestoDetalle", b =>
                {
                    b.HasOne("api_ventrix.Models.Impuesto", "Impuesto")
                        .WithMany("Impuestos")
                        .HasForeignKey("ImpuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impuesto");
                });

            modelBuilder.Entity("api_ventrix.Models.MetodoPago", b =>
                {
                    b.HasOne("api_ventrix.Models.Comprador", null)
                        .WithMany("Metodos_De_Pago")
                        .HasForeignKey("Compradorid");

                    b.HasOne("api_ventrix.Models.Negocio", null)
                        .WithMany("Metodos_Pago")
                        .HasForeignKey("Negocioid");

                    b.HasOne("api_ventrix.Models.Vendedor", null)
                        .WithMany("Metodos_De_Pago")
                        .HasForeignKey("Vendedorid");
                });

            modelBuilder.Entity("api_ventrix.Models.Pedido", b =>
                {
                    b.HasOne("api_ventrix.Models.Comprador", "Comprador")
                        .WithMany()
                        .HasForeignKey("Id_Comprador");

                    b.HasOne("api_ventrix.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("Id_Negocio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("api_ventrix.Models.Producto", b =>
                {
                    b.HasOne("api_ventrix.Models.Descuento", null)
                        .WithMany("Productos_Aplicados")
                        .HasForeignKey("DescuentoId");

                    b.HasOne("api_ventrix.Models.Factura", null)
                        .WithMany("Productos")
                        .HasForeignKey("FacturaId");

                    b.HasOne("api_ventrix.Models.Negocio", null)
                        .WithMany()
                        .HasForeignKey("Id_Negocio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api_ventrix.Models.Negocio", null)
                        .WithMany("Productos")
                        .HasForeignKey("Negocioid");
                });

            modelBuilder.Entity("api_ventrix.Models.Vendedor", b =>
                {
                    b.HasOne("api_ventrix.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("Negocioid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("PedidoItem", b =>
                {
                    b.Navigation("Impuestos_Aplicados");
                });

            modelBuilder.Entity("api_ventrix.Models.Comprador", b =>
                {
                    b.Navigation("Metodos_De_Pago");
                });

            modelBuilder.Entity("api_ventrix.Models.Descuento", b =>
                {
                    b.Navigation("Productos_Aplicados");
                });

            modelBuilder.Entity("api_ventrix.Models.Factura", b =>
                {
                    b.Navigation("Descuentos_aplicados");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("api_ventrix.Models.Impuesto", b =>
                {
                    b.Navigation("Impuestos");
                });

            modelBuilder.Entity("api_ventrix.Models.Negocio", b =>
                {
                    b.Navigation("Metodos_Pago");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("api_ventrix.Models.Pedido", b =>
                {
                    b.Navigation("PedidoItems");
                });

            modelBuilder.Entity("api_ventrix.Models.Producto", b =>
                {
                    b.Navigation("Impuestos_Aplicados");
                });

            modelBuilder.Entity("api_ventrix.Models.Vendedor", b =>
                {
                    b.Navigation("Administradores");

                    b.Navigation("Metodos_De_Pago");
                });
#pragma warning restore 612, 618
        }
    }
}
