// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_ventrix.Data;

#nullable disable

namespace api_ventrix.Migrations
{
    [DbContext(typeof(ConeccionContext))]
    partial class ConeccionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_bentrix.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("api_bentrix.Models.Carrito_Compras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion_Destino")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_Envio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Negocio");

                    b.ToTable("CarritosCompras");
                });

            modelBuilder.Entity("api_bentrix.Models.Descuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Carrito_ComprasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre_Descuento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo_Descuento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor_Aplica")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_Max")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Valor_Min")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Carrito_ComprasId");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("api_bentrix.Models.Impuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Impuestos");
                });

            modelBuilder.Entity("api_bentrix.Models.ImpuestoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImpuestoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImpuestoId");

                    b.ToTable("ImpuestoDetalle");
                });

            modelBuilder.Entity("api_bentrix.Models.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompradorId")
                        .HasColumnType("int");

                    b.Property<int?>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("NegocioId");

                    b.HasIndex("VendedorId");

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("api_bentrix.Models.Negocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.PrimitiveCollection<string>("Imagenes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlLogo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Negocios");
                });

            modelBuilder.Entity("api_bentrix.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Clave_Hasheada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Numero_Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tipo_Documento")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator().HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("api_bentrix.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<int?>("Carrito_ComprasId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo_Lote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DescuentoId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Carrito_ComprasId");

                    b.HasIndex("DescuentoId");

                    b.HasIndex("Id_Negocio");

                    b.HasIndex("NegocioId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("api_bentrix.Models.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<int>("Id_Vendedor")
                        .HasColumnType("int");

                    b.Property<int>("Tipo_Reporte")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("api_bentrix.Models.Administrador", b =>
                {
                    b.HasBaseType("api_bentrix.Models.Persona");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.Property<int>("Nivel_Acceso")
                        .HasColumnType("int");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("int");

                    b.HasIndex("Id_Negocio");

                    b.HasIndex("VendedorId");

                    b.ToTable("Personas", t =>
                        {
                            t.Property("Id_Negocio")
                                .HasColumnName("Administrador_Id_Negocio");
                        });

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("api_bentrix.Models.Comprador", b =>
                {
                    b.HasBaseType("api_bentrix.Models.Persona");

                    b.Property<int>("Carrito_ComprasId")
                        .HasColumnType("int");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Negocio")
                        .HasColumnType("int");

                    b.HasIndex("Carrito_ComprasId");

                    b.HasIndex("Id_Negocio");

                    b.HasDiscriminator().HasValue("Comprador");
                });

            modelBuilder.Entity("api_bentrix.Models.Vendedor", b =>
                {
                    b.HasBaseType("api_bentrix.Models.Persona");

                    b.Property<DateTime>("Fecha_Fin_Plan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio_Plan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("NegocioId");

                    b.HasDiscriminator().HasValue("Vendedor");
                });

            modelBuilder.Entity("api_bentrix.Models.Carrito_Compras", b =>
                {
                    b.HasOne("api_bentrix.Models.Negocio", null)
                        .WithMany()
                        .HasForeignKey("Id_Negocio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("api_bentrix.Models.Descuento", b =>
                {
                    b.HasOne("api_bentrix.Models.Carrito_Compras", null)
                        .WithMany("Descuentos_Aplicados")
                        .HasForeignKey("Carrito_ComprasId");
                });

            modelBuilder.Entity("api_bentrix.Models.Impuesto", b =>
                {
                    b.HasOne("api_bentrix.Models.Producto", null)
                        .WithMany("Impuestos_Aplicados")
                        .HasForeignKey("ProductoId");
                });

            modelBuilder.Entity("api_bentrix.Models.ImpuestoDetalle", b =>
                {
                    b.HasOne("api_bentrix.Models.Impuesto", "Impuesto")
                        .WithMany("Impuestos")
                        .HasForeignKey("ImpuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impuesto");
                });

            modelBuilder.Entity("api_bentrix.Models.MetodoPago", b =>
                {
                    b.HasOne("api_bentrix.Models.Comprador", null)
                        .WithMany("Metodos_De_Pago")
                        .HasForeignKey("CompradorId");

                    b.HasOne("api_bentrix.Models.Negocio", null)
                        .WithMany("Metodos_Pago")
                        .HasForeignKey("NegocioId");

                    b.HasOne("api_bentrix.Models.Vendedor", null)
                        .WithMany("Metodos_De_Pago")
                        .HasForeignKey("VendedorId");
                });

            modelBuilder.Entity("api_bentrix.Models.Producto", b =>
                {
                    b.HasOne("api_bentrix.Models.Carrito_Compras", null)
                        .WithMany("Productos")
                        .HasForeignKey("Carrito_ComprasId");

                    b.HasOne("api_bentrix.Models.Descuento", null)
                        .WithMany("Productos_Aplicados")
                        .HasForeignKey("DescuentoId");

                    b.HasOne("api_bentrix.Models.Negocio", null)
                        .WithMany()
                        .HasForeignKey("Id_Negocio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api_bentrix.Models.Negocio", null)
                        .WithMany("Productos")
                        .HasForeignKey("NegocioId");
                });

            modelBuilder.Entity("api_bentrix.Models.Administrador", b =>
                {
                    b.HasOne("api_bentrix.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("Id_Negocio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("api_bentrix.Models.Vendedor", null)
                        .WithMany("Administradores")
                        .HasForeignKey("VendedorId");

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("api_bentrix.Models.Comprador", b =>
                {
                    b.HasOne("api_bentrix.Models.Carrito_Compras", "Carrito_Compras")
                        .WithMany()
                        .HasForeignKey("Carrito_ComprasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_bentrix.Models.Negocio", null)
                        .WithMany()
                        .HasForeignKey("Id_Negocio")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Carrito_Compras");
                });

            modelBuilder.Entity("api_bentrix.Models.Vendedor", b =>
                {
                    b.HasOne("api_bentrix.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("api_bentrix.Models.Carrito_Compras", b =>
                {
                    b.Navigation("Descuentos_Aplicados");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("api_bentrix.Models.Descuento", b =>
                {
                    b.Navigation("Productos_Aplicados");
                });

            modelBuilder.Entity("api_bentrix.Models.Impuesto", b =>
                {
                    b.Navigation("Impuestos");
                });

            modelBuilder.Entity("api_bentrix.Models.Negocio", b =>
                {
                    b.Navigation("Metodos_Pago");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("api_bentrix.Models.Producto", b =>
                {
                    b.Navigation("Impuestos_Aplicados");
                });

            modelBuilder.Entity("api_bentrix.Models.Comprador", b =>
                {
                    b.Navigation("Metodos_De_Pago");
                });

            modelBuilder.Entity("api_bentrix.Models.Vendedor", b =>
                {
                    b.Navigation("Administradores");

                    b.Navigation("Metodos_De_Pago");
                });
#pragma warning restore 612, 618
        }
    }
}
